const mongoose = require("mongoose");

const reportSchema = new mongoose.Schema({
  reportId: {
    type:    String,
    unique:  true,
    default: ""   // generated by server before save
  },
  pageId: {
    type: mongoose.Schema.Types.ObjectId,
    ref:  "Candidate"
  },
  candidateName: { type: String, default: "" },   // denormalised for admin display
  partyName:     { type: String, default: "" },   // used in reportId generation
  message:       { type: String, required: true },
  status: {
    type:    String,
    enum:    ["pending", "reviewed", "resolved"],
    default: "pending"
  },
  adminReply: { type: String, default: "" },
  repliedAt:  Date
}, { timestamps: true });

module.exports = mongoose.model("Report", reportSchema);